window.VOCABULARY_CARDS = [
  {
    "word": "indisputably",
    "ipa": "/ˌɪndɪˈspjutəbli/",
    "image": "assets/images/01-indisputably.jpg",
    "imageAlt": "judge gavel",
    "audio": "assets/audio/01-indisputably.mp3",
    "definition": "in a way that cannot be argued with",
    "zh": "无可争辩地",
    "sentenceZh": "香港半岛酒店无可争辩地是全世界最具标志性的酒店之一.",
    "sentence": "The Peninsula Hong Kong is indisputably one of the most iconic hotels in the entire world.",
    "match": "indisputably"
  },
  {
    "word": "staple",
    "ipa": "/ˈsteɪpəl/",
    "image": "assets/images/02-staple.jpg",
    "imageAlt": "Peninsula Hotel Hong Kong exterior",
    "audio": "assets/audio/02-staple.mp3",
    "definition": "a basic or essential item that is always there",
    "zh": "常青树,标配",
    "sentenceZh": "它是香港酒店业的常青树,已经97年了.",
    "sentence": "It is a staple of Hong Kong hospitality, and has been for 97 years.",
    "match": "staple"
  },
  {
    "word": "ambiance",
    "ipa": "/ˈæmbiəns/",
    "image": "assets/images/03-ambiance.jpg",
    "imageAlt": "luxury hotel lobby atmosphere",
    "audio": "assets/audio/03-ambiance.mp3",
    "definition": "the character and atmosphere of a place",
    "zh": "氛围",
    "sentenceZh": "评分维度一如既往:氛围,房间,餐饮,服务,以及X因素.",
    "sentence": "The categories, like always, are: The Ambiance, The Room, The Dining, The Service and The It-Factor.",
    "match": "Ambiance"
  },
  {
    "word": "take a peek",
    "ipa": "/teɪk ə pik/",
    "image": "assets/images/04-take-a-peek.jpg",
    "imageAlt": "take a peek",
    "audio": "assets/audio/04-take-a-peek.mp3",
    "definition": "to look quickly at something",
    "zh": "快速看一眼",
    "sentenceZh": "在逛酒店其余部分之前,先让我们快速看一眼.",
    "sentence": "Let's take a peek at it before we see the rest of the hotel.",
    "match": "take a peek"
  },
  {
    "word": "right out of the gate",
    "ipa": "/raɪt aʊt əv ðə ɡeɪt/",
    "image": "assets/images/05-right-out-of-the-gate.jpg",
    "imageAlt": "right out of the gate",
    "audio": "assets/audio/05-right-out-of-the-gate.mp3",
    "definition": "immediately, from the very beginning",
    "zh": "一开始,一进门就",
    "sentenceZh": "它真的是一进门就把那段历史展示给你看.",
    "sentence": "It really does start to show you that history right out of the gate.",
    "match": "right out of the gate"
  },
  {
    "word": "gargoyle",
    "ipa": "/ˈɡɑrˌɡɔɪl/",
    "image": "assets/images/06-gargoyle.jpg",
    "imageAlt": "stone gargoyle architecture close up",
    "audio": "assets/audio/06-gargoyle.mp3",
    "definition": "a stone carving of a strange creature on a building",
    "zh": "石像鬼(建筑怪兽雕饰)",
    "sentenceZh": "实际上,这个房间的檐口和柱子上有76张石像鬼面孔.",
    "sentence": "In fact, there are over 76 gargoyle faces that are all in the crown molding and around the different pillars that are in this room.",
    "match": "gargoyle"
  },
  {
    "word": "molding",
    "ipa": "/ˈmoʊldɪŋ/",
    "image": "assets/images/07-molding.jpg",
    "imageAlt": "molding",
    "audio": "assets/audio/07-molding.mp3",
    "definition": "a decorative strip of wood or plaster along the top of a wall",
    "zh": "檐口线脚",
    "sentenceZh": "这个房间的檐口和柱子上共有76张石像鬼面孔.",
    "sentence": "There are over 76 gargoyle faces that are all in the crown molding and around the different pillars that are in this room.",
    "match": "molding"
  },
  {
    "word": "pillar",
    "ipa": "/ˈpɪlər/",
    "image": "assets/images/08-pillar.jpg",
    "imageAlt": "pillar",
    "audio": "assets/audio/08-pillar.mp3",
    "definition": "a tall vertical column that supports a building",
    "zh": "柱子",
    "sentenceZh": "这个房间的檐口和柱子上共有76张石像鬼面孔.",
    "sentence": "There are over 76 gargoyle faces that are all in the crown molding and around the different pillars that are in this room.",
    "match": "pillars"
  },
  {
    "word": "deities",
    "ipa": "/ˈdiətiz/",
    "image": "assets/images/09-deities.jpg",
    "imageAlt": "Chinese deities statues",
    "audio": "assets/audio/09-deities.mp3",
    "definition": "gods or goddesses",
    "zh": "神祇",
    "sentenceZh": "这里有许多不同的神祇和偶像,据说能守护员工和客人.",
    "sentence": "There are many different gods and deities and different idols that they believe protect the staff and the guests, which is a theme in this hotel.",
    "match": "deities"
  },
  {
    "word": "idol",
    "ipa": "/ˈaɪdəl/",
    "image": "assets/images/10-idol.jpg",
    "imageAlt": "idol",
    "audio": "assets/audio/10-idol.mp3",
    "definition": "a statue or image that is worshipped",
    "zh": "神像,偶像",
    "sentenceZh": "这里有许多不同的神祇和偶像,据说能守护员工和客人.",
    "sentence": "There are many different gods and deities and different idols that they believe protect the staff and the guests.",
    "match": "idols"
  },
  {
    "word": "helipad",
    "ipa": "/ˈhɛliˌpæd/",
    "image": "assets/images/11-helipad.jpg",
    "imageAlt": "rooftop helipad",
    "audio": "assets/audio/11-helipad.mp3",
    "definition": "a landing area for helicopters",
    "zh": "直升机停机坪",
    "sentenceZh": "这是一个带两个直升机停机坪的屋顶酒廊,你可以按每分钟1000港币坐直升机.",
    "sentence": "It is a two helipad rooftop lounge location where you can literally take helicopter rides for 1,000 Hong Kong dollars per minute.",
    "match": "helipad"
  },
  {
    "word": "rooftop",
    "ipa": "/ˈrufˌtɑp/",
    "image": "assets/images/12-rooftop.jpg",
    "imageAlt": "rooftop",
    "audio": "assets/audio/12-rooftop.mp3",
    "definition": "on or relating to the top of a building",
    "zh": "屋顶的",
    "sentenceZh": "这是一个带两个直升机停机坪的屋顶酒廊,你真的可以坐直升机.",
    "sentence": "It is a two helipad rooftop lounge location where you can literally take helicopter rides.",
    "match": "rooftop"
  },
  {
    "word": "serene",
    "ipa": "/sərˈin/",
    "image": "assets/images/13-serene.jpg",
    "imageAlt": "serene calm lake",
    "audio": "assets/audio/13-serene.mp3",
    "definition": "calm, peaceful and quiet",
    "zh": "宁静的",
    "sentenceZh": "在夏天,他们打开窗户,外面就是香港和海湾,非常宁静.",
    "sentence": "Now up on the eighth floor is the indoor Roman-inspired heated swimming pool. And in the summer, they open up the windows here that look out into Hong Kong and the bay. It is so serene.",
    "match": "serene"
  },
  {
    "word": "standout",
    "ipa": "/ˈstænˌdaʊt/",
    "image": "assets/images/14-standout.jpg",
    "imageAlt": "standout",
    "audio": "assets/audio/14-standout.mp3",
    "definition": "something that is noticeably better than others",
    "zh": "佼佼者,亮点",
    "sentenceZh": "它是一座罗马浴场,绝对是酒店氛围中的亮点.",
    "sentence": "It's a Roman bath house, definitely a standout in the Ambiance of the hotel.",
    "match": "standout"
  },
  {
    "word": "reinvigoration",
    "ipa": "/ˌriɪnˌvɪɡərˈeɪʃən/",
    "image": "assets/images/15-reinvigoration.jpg",
    "imageAlt": "spa massage wellness relaxation",
    "audio": "assets/audio/15-reinvigoration.mp3",
    "definition": "the feeling of being refreshed and re-energized",
    "zh": "重焕活力",
    "sentenceZh": "他们的招牌护理旨在让人全身重焕活力.",
    "sentence": "Their signature treatment here is called the Han treatment, that has pressure point dry massage mixed with scalp massage, and it's meant to be a total body reinvigoration.",
    "match": "reinvigoration"
  },
  {
    "word": "scalp",
    "ipa": "/ˈskælp/",
    "image": "assets/images/16-scalp.jpg",
    "imageAlt": "scalp",
    "audio": "assets/audio/16-scalp.mp3",
    "definition": "the skin on top of your head",
    "zh": "头皮",
    "sentenceZh": "招牌护理包含穴位干压按摩和头皮按摩.",
    "sentence": "Their signature treatment has pressure point dry massage mixed with scalp massage.",
    "match": "scalp"
  },
  {
    "word": "hammam",
    "ipa": "/hɑˈmɑm/",
    "image": "assets/images/17-hammam.jpg",
    "imageAlt": "traditional hammam interior",
    "audio": "assets/audio/17-hammam.mp3",
    "definition": "a traditional steam bath",
    "zh": "土耳其浴(蒸汽浴室)",
    "sentenceZh": "等候区有水晶土耳其蒸汽浴室和干蒸桑拿.",
    "sentence": "All right, got my Peninsula spa robe on, and here in the waiting area, they have ice that you can put all over your face or body, a crystal hammam steam room, dry sauna.",
    "match": "hammam"
  },
  {
    "word": "sauna",
    "ipa": "/ˈsɔnə/",
    "image": "assets/images/18-sauna.jpg",
    "imageAlt": "sauna",
    "audio": "assets/audio/18-sauna.mp3",
    "definition": "a hot room used for sweating and relaxing",
    "zh": "桑拿",
    "sentenceZh": "等候区有敷脸敷身体的冰块,水晶土耳其蒸汽房和干蒸桑拿.",
    "sentence": "Here in the waiting area, they have ice that you can put all over your face or body, a crystal hammam steam room, dry sauna.",
    "match": "sauna"
  },
  {
    "word": "overlooking",
    "ipa": "/ˌoʊvərˈlʊkɪŋ/",
    "image": "assets/images/19-overlooking.jpg",
    "imageAlt": "overlooking",
    "audio": "assets/audio/19-overlooking.mp3",
    "definition": "having a view of something from above",
    "zh": "俯瞰",
    "sentenceZh": "浴缸正对海港,景色绝美.",
    "sentence": "Absolutely beautiful tub overlooking the harbor here.",
    "match": "overlooking"
  },
  {
    "word": "segmented",
    "ipa": "/ˈsɛɡˌmɛntɪd/",
    "image": "assets/images/20-segmented.jpg",
    "imageAlt": "segmented",
    "audio": "assets/audio/20-segmented.mp3",
    "definition": "divided into separate parts",
    "zh": "被分割的",
    "sentenceZh": "酒店大部分在楼内,分为老楼和新楼两部分.",
    "sentence": "So most of the hotel, of course, is inside the building, which is segmented by the old building and the new building.",
    "match": "segmented"
  },
  {
    "word": "orchid",
    "ipa": "/ˈɔrkɪd/",
    "image": "assets/images/21-orchid.jpg",
    "imageAlt": "orchid",
    "audio": "assets/audio/21-orchid.mp3",
    "definition": "a delicate flower, often grown indoors",
    "zh": "兰花",
    "sentenceZh": "从大型兰花陈列到大堂花卉,酒店里你看到的所有花都是真的.",
    "sentence": "All of the flowers that you see throughout the hotel are real, from the major orchid displays, to the flowers in the lobby, all real.",
    "match": "orchid"
  },
  {
    "word": "assortment",
    "ipa": "/əˈsɔrtmənt/",
    "image": "assets/images/22-assortment.jpg",
    "imageAlt": "assortment",
    "audio": "assets/audio/22-assortment.mp3",
    "definition": "a varied collection of different things",
    "zh": "花色繁多的组合",
    "sentenceZh": "这大概是我住过的酒店里见过的最全的酒店周边商品阵容.",
    "sentence": "Probably the largest assortment of hotel branded items that I've ever seen at any one of these stays.",
    "match": "assortment"
  },
  {
    "word": "aesthetic",
    "ipa": "/ɛsˈθɛtɪk/",
    "image": "assets/images/23-aesthetic.jpg",
    "imageAlt": "elegant interior design aesthetic",
    "audio": "assets/audio/23-aesthetic.mp3",
    "definition": "concerned with beauty and good looks",
    "zh": "美观的",
    "sentenceZh": "健身房远算不上我们见过的最美观,最漂亮的.",
    "sentence": "On the flip side of things, the gym is definitely far from the most aesthetic or beautiful or updated that we've seen.",
    "match": "aesthetic"
  },
  {
    "word": "motif",
    "ipa": "/moʊˈtif/",
    "image": "assets/images/24-motif.png",
    "imageAlt": "repeating blue and gold floral motif on ceramic tiles",
    "audio": "assets/audio/24-motif.mp3",
    "definition": "a repeated decorative theme or pattern",
    "zh": "母题,装饰主题",
    "sentenceZh": "就这样把这个母题和主题延续到酒店各处.",
    "sentence": "So, it just continues the motif and theme through the hotel.",
    "match": "motif"
  },
  {
    "word": "mildew",
    "ipa": "/ˈmɪlˌdu/",
    "image": "assets/images/25-mildew.jpg",
    "imageAlt": "mildew",
    "audio": "assets/audio/25-mildew.mp3",
    "definition": "a fungus that grows in damp places",
    "zh": "霉斑,霉菌",
    "sentenceZh": "半岛酒店确实存在霉菌问题.",
    "sentence": "They definitely are dealing with a mold/mildew issue in The Peninsula.",
    "match": "mildew"
  },
  {
    "word": "humid",
    "ipa": "/ˈhjumɪd/",
    "image": "assets/images/26-humid.jpg",
    "imageAlt": "humid",
    "audio": "assets/audio/26-humid.mp3",
    "definition": "warm and damp",
    "zh": "潮湿的",
    "sentenceZh": "这里很潮湿,香港雨水很多.",
    "sentence": "Now it's humid. It rains a lot in Hong Kong.",
    "match": "humid"
  },
  {
    "word": "allergies",
    "ipa": "/ˈælərdʒiz/",
    "image": "assets/images/27-allergies.jpg",
    "imageAlt": "allergies",
    "audio": "assets/audio/27-allergies.mp3",
    "definition": "bad reactions to things like pollen, dust or certain foods",
    "zh": "过敏",
    "sentenceZh": "我知道很多观众可能对霉菌过敏.",
    "sentence": "I know many of you watching may have allergies to mold or mildew.",
    "match": "allergies"
  },
  {
    "word": "valet",
    "ipa": "/væˈleɪ/",
    "image": "assets/images/28-valet.jpg",
    "imageAlt": "valet",
    "audio": "assets/audio/28-valet.mp3",
    "definition": "a hotel service that parks cars or collects items for guests",
    "zh": "代客服务(箱)",
    "sentenceZh": "首先是代客服务箱:按下按钮打开,箱子直通走廊,工作人员不进房间就能取送物品.",
    "sentence": "Number one, the valet box. You push this button, it opens up, and there's a valet collection box that goes right into the hallway here.",
    "match": "valet"
  },
  {
    "word": "manicure",
    "ipa": "/ˈmænɪkjʊr/",
    "image": "assets/images/29-manicure.jpg",
    "imageAlt": "manicure",
    "audio": "assets/audio/29-manicure.mp3",
    "definition": "cosmetic care for the hands and nails",
    "zh": "美甲",
    "sentenceZh": "以防你在房间里给自己做了美甲.",
    "sentence": "In case you gave yourself a manicure in the room.",
    "match": "manicure"
  },
  {
    "word": "fax",
    "ipa": "/ˈfæks/",
    "image": "assets/images/30-fax.jpg",
    "imageAlt": "fax",
    "audio": "assets/audio/30-fax.mp3",
    "definition": "a machine that sends copies of documents over phone lines",
    "zh": "传真机",
    "sentenceZh": "下面还有一台完整的传真机.",
    "sentence": "Down below, there's a full fax machine in the room.",
    "match": "fax"
  },
  {
    "word": "amenities",
    "ipa": "/əˈmɛnətiz/",
    "image": "assets/images/31-amenities.jpg",
    "imageAlt": "luxury hotel bathroom amenities",
    "audio": "assets/audio/31-amenities.mp3",
    "definition": "useful facilities or items provided for guests",
    "zh": "便利设施",
    "sentenceZh": "打开这里就是电视,下面是你的零食,备品和玻璃器皿.",
    "sentence": "Slightly less strange, but still interesting: this area behind me looks like there may not be anything there, but watch this - open here's the TV, down here your snacks and amenities and glassware.",
    "match": "amenities"
  },
  {
    "word": "glassware",
    "ipa": "/ˈɡlæˌswɛr/",
    "image": "assets/images/32-glassware.jpg",
    "imageAlt": "glassware",
    "audio": "assets/audio/32-glassware.mp3",
    "definition": "drinking glasses and similar items",
    "zh": "玻璃器皿",
    "sentenceZh": "下面是你的零食,备品和玻璃器皿.",
    "sentence": "Down here your snacks and amenities and glassware.",
    "match": "glassware"
  },
  {
    "word": "dijon",
    "ipa": "/ˈdiʒɑn/",
    "image": "assets/images/33-dijon.jpg",
    "imageAlt": "dijon",
    "audio": "assets/audio/33-dijon.mp3",
    "definition": "a type of French mustard",
    "zh": "第戎芥末",
    "sentenceZh": "有Kettle蜂蜜第戎芥末味薯片.",
    "sentence": "You've got Kettle honey dijon chips.",
    "match": "dijon"
  },
  {
    "word": "gummy",
    "ipa": "/ˈɡʌmi/",
    "image": "assets/images/34-gummy.jpg",
    "imageAlt": "gummy",
    "audio": "assets/audio/34-gummy.mp3",
    "definition": "chewy and soft, like gummy candy",
    "zh": "软糖的,Q弹的",
    "sentenceZh": "还有半岛小熊软糖.",
    "sentence": "And some Peninsula gummy bears.",
    "match": "gummy"
  },
  {
    "word": "tonic",
    "ipa": "/ˈtɑnɪk/",
    "image": "assets/images/35-tonic.jpg",
    "imageAlt": "tonic",
    "audio": "assets/audio/35-tonic.mp3",
    "definition": "a bitter fizzy drink often mixed with gin",
    "zh": "汤力水",
    "sentenceZh": "饮品很简单:水,汤力水,雪碧,可乐,红牛.",
    "sentence": "Very simple drinks: waters, tonic water, Sprite, Coke, Red Bull.",
    "match": "tonic"
  },
  {
    "word": "quirky",
    "ipa": "/ˈkwɜrki/",
    "image": "assets/images/36-quirky.jpg",
    "imageAlt": "quirky",
    "audio": "assets/audio/36-quirky.mp3",
    "definition": "odd in a charming or unusual way",
    "zh": "古怪有趣的",
    "sentenceZh": "现在看浴室,如我所说,这里也有几处古怪的设计.",
    "sentence": "Now into the bathroom, as I mentioned, there are a couple quirky things in here as well.",
    "match": "quirky"
  },
  {
    "word": "revolve",
    "ipa": "/riˈvɑlv/",
    "image": "assets/images/37-revolve.jpg",
    "imageAlt": "revolve",
    "audio": "assets/audio/37-revolve.mp3",
    "definition": "to center on; to turn around a central point",
    "zh": "围绕;旋转",
    "sentenceZh": "这里的几处古怪设计主要围绕着这些老式电话.",
    "sentence": "There are a couple quirky things in here as well, which mainly revolve around these old phones.",
    "match": "revolve"
  },
  {
    "word": "marbling",
    "ipa": "/ˈmɑrbəlɪŋ/",
    "image": "assets/images/38-marbling.jpg",
    "imageAlt": "marble surface veining close up",
    "audio": "assets/audio/38-marbling.mp3",
    "definition": "the veined pattern like marble",
    "zh": "大理石纹理",
    "sentenceZh": "纸巾盒也融入了这里的大理石纹理.",
    "sentence": "There's also the tissue holder, which is worked into the marbling here.",
    "match": "marbling"
  },
  {
    "word": "faucet",
    "ipa": "/ˈfɔsət/",
    "image": "assets/images/39-faucet.jpg",
    "imageAlt": "faucet",
    "audio": "assets/audio/39-faucet.mp3",
    "definition": "a tap for controlling water (US)",
    "zh": "水龙头",
    "sentenceZh": "那个开关控制手持龙头.",
    "sentence": "That turns on the hand faucet.",
    "match": "faucet"
  },
  {
    "word": "dripping",
    "ipa": "/ˈdrɪpɪŋ/",
    "image": "assets/images/40-dripping.jpg",
    "imageAlt": "dripping",
    "audio": "assets/audio/40-dripping.mp3",
    "definition": "falling in small drops",
    "zh": "滴水的",
    "sentenceZh": "而且这里还在滴水,实在不太好用.",
    "sentence": "And then still, this is dripping over here, so not very easy to use at all.",
    "match": "dripping"
  },
  {
    "word": "hose",
    "ipa": "/ˈhoʊz/",
    "image": "assets/images/41-hose.jpg",
    "imageAlt": "hose",
    "audio": "assets/audio/41-hose.mp3",
    "definition": "a flexible tube for carrying water",
    "zh": "软管,水枪",
    "sentenceZh": "每次进去都像被消防水枪或高压水枪冲洗.",
    "sentence": "It feels like a fire hose or like you are being power washed every time you get in.",
    "match": "hose"
  },
  {
    "word": "exfoliate",
    "ipa": "/ɛksˈfoʊlieɪt/",
    "image": "assets/images/42-exfoliate.jpg",
    "imageAlt": "exfoliate",
    "audio": "assets/audio/42-exfoliate.mp3",
    "definition": "to remove dead skin cells by rubbing",
    "zh": "去角质",
    "sentenceZh": "淋浴水压大到让我感觉被去了层角质.",
    "sentence": "I feel exfoliated because of how hard the pressure is in the shower.",
    "match": "exfoliated"
  },
  {
    "word": "plumbing",
    "ipa": "/ˈplʌmɪŋ/",
    "image": "assets/images/43-plumbing.jpg",
    "imageAlt": "plumbing",
    "audio": "assets/audio/43-plumbing.mp3",
    "definition": "the system of pipes in a building",
    "zh": "管道系统",
    "sentenceZh": "而且管道系统相当老旧.",
    "sentence": "Also the plumbing is quite old.",
    "match": "plumbing"
  },
  {
    "word": "gargle",
    "ipa": "/ˈɡɑrɡəl/",
    "image": "assets/images/44-gargle.jpg",
    "imageAlt": "gargle",
    "audio": "assets/audio/44-gargle.mp3",
    "definition": "to bubble liquid in the back of your throat",
    "zh": "漱口;咕噜作响",
    "sentenceZh": "开淋浴时,水还会从洗手盆里咕噜咕噜地冒出来.",
    "sentence": "When you turn on the shower, it gargles through the sink as well.",
    "match": "gargles"
  },
  {
    "word": "unpleasant",
    "ipa": "/ənˈplɛzənt/",
    "image": "assets/images/45-unpleasant.jpg",
    "imageAlt": "unpleasant",
    "audio": "assets/audio/45-unpleasant.mp3",
    "definition": "not enjoyable; disagreeable",
    "zh": "令人不快的",
    "sentenceZh": "这让整个体验再次变得很不愉快.",
    "sentence": "Which just makes the entire thing, again, unpleasant.",
    "match": "unpleasant"
  },
  {
    "word": "penthouse",
    "ipa": "/ˈpɛntˌhaʊs/",
    "image": "assets/images/46-penthouse.jpg",
    "imageAlt": "luxury penthouse interior skyline",
    "audio": "assets/audio/46-penthouse.mp3",
    "definition": "a luxury apartment on the top floor",
    "zh": "顶层套房",
    "sentenceZh": "但正如我说的,这里还有另外两间顶层套房.",
    "sentence": "So that is the base level room. But as I mentioned, there are two other penthouse suites here.",
    "match": "penthouse"
  },
  {
    "word": "complimentary",
    "ipa": "/ˌkɑmpləˈmɛntri/",
    "image": "assets/images/47-complimentary.jpg",
    "imageAlt": "complimentary hotel breakfast tray",
    "audio": "assets/audio/47-complimentary.mp3",
    "definition": "given for free",
    "zh": "免费赠送的",
    "sentenceZh": "入住时会免费赠送一些盒子,里面有小肥皂可以带回家.",
    "sentence": "However, there are some incredible details, like the amenities that you receive complimentary when you stay here, include these boxes with little soaps that you can take home.",
    "match": "complimentary"
  },
  {
    "word": "perk",
    "ipa": "/ˈpɜrk/",
    "image": "assets/images/48-perk.jpg",
    "imageAlt": "perk",
    "audio": "assets/audio/48-perk.mp3",
    "definition": "an extra benefit or advantage",
    "zh": "额外福利",
    "sentenceZh": "这是这间房一个很棒的额外福利.",
    "sentence": "So this is a really nice perk to the room.",
    "match": "perk"
  },
  {
    "word": "duvet",
    "ipa": "/duˈveɪ/",
    "image": "assets/images/49-duvet.jpg",
    "imageAlt": "white duvet hotel bed",
    "audio": "assets/audio/49-duvet.mp3",
    "definition": "a soft quilt filled with down or fiber",
    "zh": "羽绒被",
    "sentenceZh": "但我要说,羽绒被套,床单尤其是枕头都非常柔软.",
    "sentence": "Okay, so the bed is quite firm. The mattress itself is more like a brick than a mattress, but, I will say the duvet cover and the sheets and the pillows especially are so soft.",
    "match": "duvet"
  },
  {
    "word": "tempting",
    "ipa": "/ˈtɛmptɪŋ/",
    "image": "assets/images/50-tempting.jpg",
    "imageAlt": "tempting",
    "audio": "assets/audio/50-tempting.mp3",
    "definition": "attractive and hard to resist",
    "zh": "诱人的",
    "sentenceZh": "这些葡萄从放进来的那一刻起就一直在诱惑我.",
    "sentence": "These grapes have been tempting me, literally since they put them in here.",
    "match": "tempting"
  },
  {
    "word": "appetizing",
    "ipa": "/ˈæpɪˌtaɪzɪŋ/",
    "image": "assets/images/51-appetizing.jpg",
    "imageAlt": "appetizing",
    "audio": "assets/audio/51-appetizing.mp3",
    "definition": "looking or smelling delicious",
    "zh": "开胃诱人的",
    "sentenceZh": "有几道菜可能不如其他的那么开胃.",
    "sentence": "There's a couple of dishes that maybe aren't as appetizing as the others.",
    "match": "appetizing"
  },
  {
    "word": "custard",
    "ipa": "/ˈkʌstərd/",
    "image": "assets/images/52-custard.jpg",
    "imageAlt": "custard",
    "audio": "assets/audio/52-custard.mp3",
    "definition": "a sweet sauce made from milk, eggs and sugar",
    "zh": "奶黄,卡仕达",
    "sentenceZh": "第二样是他们手工制作的奶黄月饼.",
    "sentence": "Number two is their handmade custard mooncakes.",
    "match": "custard"
  },
  {
    "word": "mooncake",
    "ipa": "/ˈmunˌkeɪk/",
    "image": "assets/images/53-mooncake.jpg",
    "imageAlt": "mooncake",
    "audio": "assets/audio/53-mooncake.mp3",
    "definition": "a Chinese pastry traditionally eaten at Mid-Autumn Festival",
    "zh": "月饼",
    "sentenceZh": "第二样是他们手工制作的奶黄月饼.",
    "sentence": "Number two is their handmade custard mooncakes.",
    "match": "mooncakes"
  },
  {
    "word": "sommelier",
    "ipa": "/ˌsəməlˈjeɪ/",
    "image": "assets/images/54-sommelier.jpg",
    "imageAlt": "sommelier serving wine restaurant",
    "audio": "assets/audio/54-sommelier.mp3",
    "definition": "a wine or tea expert who advises on drinks",
    "zh": "侍酒师,侍茶师",
    "sentenceZh": "他们有茶艺师加热小茶杯,作为接下来这道菜的味觉提香.",
    "sentence": "So they have a tea sommelier heating up little tea cups to then be presented as a flavor enhancer for the dish that we're about to be served.",
    "match": "sommelier"
  },
  {
    "word": "enhancer",
    "ipa": "/ɛnˈhænsər/",
    "image": "assets/images/55-enhancer.jpg",
    "imageAlt": "enhancer",
    "audio": "assets/audio/55-enhancer.mp3",
    "definition": "something that makes a quality stronger",
    "zh": "增强剂,提味",
    "sentenceZh": "作为接下来这道菜的提味之用.",
    "sentence": "To then be presented as a flavor enhancer for the dish.",
    "match": "enhancer"
  },
  {
    "word": "brew",
    "ipa": "/ˈbru/",
    "image": "assets/images/56-brew.jpg",
    "imageAlt": "brew",
    "audio": "assets/audio/56-brew.mp3",
    "definition": "tea or coffee made by steeping; a cup of it",
    "zh": "冲泡;一杯(茶/咖啡)",
    "sentenceZh": "他们端上一杯冷萃茶.",
    "sentence": "They bring out a cold brew tea.",
    "match": "brew"
  },
  {
    "word": "astringent",
    "ipa": "/əˈstrɪndʒənt/",
    "image": "assets/images/57-astringent.png",
    "imageAlt": "strong black tea tasting",
    "audio": "assets/audio/57-astringent.mp3",
    "definition": "sharp and drying in taste",
    "zh": "涩口的",
    "sentenceZh": "茉莉花茶很容易变涩,说明茶叶泡过头了.",
    "sentence": "Oh, wow. One thing with jasmine, it can very easily become astringent. It just means that you're over-steeping the tea leaves, whether it's cold or hot.",
    "match": "astringent"
  },
  {
    "word": "jasmine",
    "ipa": "/ˈdʒæzmɪn/",
    "image": "assets/images/58-jasmine.jpg",
    "imageAlt": "jasmine",
    "audio": "assets/audio/58-jasmine.mp3",
    "definition": "a fragrant white flower, also a type of tea",
    "zh": "茉莉花(茶)",
    "sentenceZh": "茉莉花茶有一点:它很容易变涩.",
    "sentence": "One thing with jasmine, it can very easily become astringent.",
    "match": "jasmine"
  },
  {
    "word": "steep",
    "ipa": "/ˈstip/",
    "image": "assets/images/59-steep.jpg",
    "imageAlt": "steep",
    "audio": "assets/audio/59-steep.mp3",
    "definition": "to soak in liquid to extract flavor",
    "zh": "浸泡",
    "sentenceZh": "意思就是你泡茶叶泡过头了.",
    "sentence": "It just means that you're over-steeping the tea leaves.",
    "match": "steeping"
  },
  {
    "word": "vibrant",
    "ipa": "/ˈvaɪbrənt/",
    "image": "assets/images/60-vibrant.png",
    "imageAlt": "vibrant",
    "audio": "assets/audio/60-vibrant.mp3",
    "definition": "full of energy and life",
    "zh": "生机勃勃的",
    "sentenceZh": "它是座很现代的城市,同时也有非常热带,生机盎然的自然环境.",
    "sentence": "It's a very modern city, but it's a very tropical, very vibrant natural environment as well.",
    "match": "vibrant"
  },
  {
    "word": "smokiness",
    "ipa": "/ˈsmoʊkinəs/",
    "image": "assets/images/61-smokiness.jpg",
    "imageAlt": "smokiness",
    "audio": "assets/audio/61-smokiness.mp3",
    "definition": "the taste or smell of smoke",
    "zh": "烟熏味",
    "sentenceZh": "它有一种非常细腻的层次感,带点烟熏味.",
    "sentence": "It has a very delicate depth of flavor; smokiness to it, the XO sauce, of course.",
    "match": "smokiness"
  },
  {
    "word": "peking",
    "ipa": "/ˌpiˈkɪŋ/",
    "image": "assets/images/62-peking.jpg",
    "imageAlt": "peking",
    "audio": "assets/audio/62-peking.mp3",
    "definition": "relating to Beijing; Peking duck is a famous roast duck dish",
    "zh": "北京(烤鸭)",
    "sentenceZh": "这让我想起在首尔吃的北京烤鸭.",
    "sentence": "This kind of reminds me of the peking duck that we had in Seoul.",
    "match": "peking"
  },
  {
    "word": "herbaceous",
    "ipa": "/hɜrˈbeɪʃəs/",
    "image": "assets/images/63-herbaceous.jpg",
    "imageAlt": "fresh aromatic culinary herbs",
    "audio": "assets/audio/63-herbaceous.mp3",
    "definition": "tasting or smelling of fresh herbs",
    "zh": "草本清香的",
    "sentenceZh": "茶叶给鸡肉带来一种清新的草本底味.",
    "sentence": "Very tender chicken. The tea leaves give it a nice herbal, kind of herbaceous base to it.",
    "match": "herbaceous"
  },
  {
    "word": "herbal",
    "ipa": "/ˈɜrbəl/",
    "image": "assets/images/64-herbal.jpg",
    "imageAlt": "herbal",
    "audio": "assets/audio/64-herbal.mp3",
    "definition": "made from or tasting of herbs",
    "zh": "草本的",
    "sentenceZh": "茶叶给它带来清新的草本底味.",
    "sentence": "The tea leaves give it a nice herbal, kind of herbaceous base to it.",
    "match": "herbal"
  },
  {
    "word": "underwhelmed",
    "ipa": "/ˌʌndərˈwɛlmd/",
    "image": "assets/images/65-underwhelmed.jpg",
    "imageAlt": "underwhelmed disappointed expression",
    "audio": "assets/audio/65-underwhelmed.mp3",
    "definition": "disappointed; not impressed",
    "zh": "失望的",
    "sentenceZh": "第一眼看去,我对这里用的面包有些失望.",
    "sentence": "And I will say, at first glance, I'm a little bit underwhelmed with the bread that was used here and some of the other things.",
    "match": "underwhelmed"
  },
  {
    "word": "tier",
    "ipa": "/ˈtir/",
    "image": "assets/images/66-tier.jpg",
    "imageAlt": "tier",
    "audio": "assets/audio/66-tier.mp3",
    "definition": "one level of a stacked arrangement",
    "zh": "层",
    "sentenceZh": "这里有整整三层.",
    "sentence": "So you've got three different tiers here.",
    "match": "tiers"
  },
  {
    "word": "scone",
    "ipa": "/ˈskoʊn/",
    "image": "assets/images/67-scone.jpg",
    "imageAlt": "scone",
    "audio": "assets/audio/67-scone.mp3",
    "definition": "a small British cake-like bread, often eaten with tea",
    "zh": "司康",
    "sentenceZh": "最下面是司康.",
    "sentence": "And then you have the scones.",
    "match": "scones"
  },
  {
    "word": "fluffy",
    "ipa": "/ˈflʌfi/",
    "image": "assets/images/68-fluffy.jpg",
    "imageAlt": "fluffy",
    "audio": "assets/audio/68-fluffy.mp3",
    "definition": "light and soft",
    "zh": "松软的",
    "sentenceZh": "它很扎实但不干,非常松软.",
    "sentence": "It's so dense, it's not too dry, it's very fluffy.",
    "match": "fluffy"
  },
  {
    "word": "radish",
    "ipa": "/ˈrædɪʃ/",
    "image": "assets/images/69-radish.jpg",
    "imageAlt": "radish",
    "audio": "assets/audio/69-radish.mp3",
    "definition": "a small red or white root vegetable with a peppery taste",
    "zh": "小萝卜",
    "sentenceZh": "上面有一片生菜叶和一点萝卜.",
    "sentence": "A lettuce leaf and a little bit of radish on top.",
    "match": "radish"
  },
  {
    "word": "refinement",
    "ipa": "/rɪˈfaɪnmənt/",
    "image": "assets/images/70-refinement.jpg",
    "imageAlt": "refined elegant fine dining table",
    "audio": "assets/audio/70-refinement.mp3",
    "definition": "the quality of being polished and elegant",
    "zh": "精致考究",
    "sentenceZh": "我认为这里确实有提升精致度和视觉呈现的机会.",
    "sentence": "Again, I just think that there's really an opportunity here for refinement, elevation and visual improvement, but that is a very nice flavor.",
    "match": "refinement"
  },
  {
    "word": "glitter",
    "ipa": "/ˈɡlɪtər/",
    "image": "assets/images/71-glitter.jpg",
    "imageAlt": "glitter",
    "audio": "assets/audio/71-glitter.mp3",
    "definition": "tiny shiny particles used for decoration",
    "zh": "闪粉",
    "sentenceZh": "最后是草莓杯,上面撒了可食用的闪粉.",
    "sentence": "Here we have our cup of strawberries that have this edible glitter that they put on top of it.",
    "match": "glitter"
  },
  {
    "word": "edible",
    "ipa": "/ˈɛdəbəl/",
    "image": "assets/images/72-edible.jpg",
    "imageAlt": "edible",
    "audio": "assets/audio/72-edible.mp3",
    "definition": "safe to eat",
    "zh": "可食用的",
    "sentenceZh": "最后是草莓杯,上面撒了可食用的闪粉.",
    "sentence": "Here we have our cup of strawberries that have this edible glitter that they put on top of it.",
    "match": "edible"
  },
  {
    "word": "sashimi",
    "ipa": "/səˈʃimi/",
    "image": "assets/images/73-sashimi.jpg",
    "imageAlt": "sashimi",
    "audio": "assets/audio/73-sashimi.mp3",
    "definition": "thin slices of raw fish",
    "zh": "刺身",
    "sentenceZh": "他们有寿司和刺身.",
    "sentence": "They have sushi and sashimi.",
    "match": "sashimi"
  },
  {
    "word": "appetizer",
    "ipa": "/ˈæpəˌtaɪzər/",
    "image": "assets/images/74-appetizer.jpg",
    "imageAlt": "appetizer",
    "audio": "assets/audio/74-appetizer.mp3",
    "definition": "a small dish served before the main course",
    "zh": "前菜",
    "sentenceZh": "前菜盛在漂亮的托盘里端了上来.",
    "sentence": "They brought out the appetizer dish, which is on this beautiful tray.",
    "match": "appetizer"
  },
  {
    "word": "abalone",
    "ipa": "/ˌæbəˈloʊni/",
    "image": "assets/images/75-abalone.jpg",
    "imageAlt": "abalone shell seafood",
    "audio": "assets/audio/75-abalone.mp3",
    "definition": "an edible sea snail, a luxury food",
    "zh": "鲍鱼",
    "sentenceZh": "前菜盘里有番茄,白虾,豆腐和鲍鱼.",
    "sentence": "They brought out the appetizer dish, which is on this beautiful tray. So it's tomato, it's white shrimp, tofu, and abalone.",
    "match": "abalone"
  },
  {
    "word": "overpowering",
    "ipa": "/ˌoʊvərˈpaʊrɪŋ/",
    "image": "assets/images/76-overpowering.jpg",
    "imageAlt": "perfume bottle",
    "audio": "assets/audio/76-overpowering.mp3",
    "definition": "too strong or intense",
    "zh": "过于浓烈的",
    "sentenceZh": "好刺身不会过于浓烈,不会有海腥味.",
    "sentence": "You can tell when you have really great sashimi. It's not overpowering. Doesn't taste like the ocean.",
    "match": "overpowering"
  },
  {
    "word": "roe",
    "ipa": "/ˈroʊ/",
    "image": "assets/images/77-roe.jpg",
    "imageAlt": "roe",
    "audio": "assets/audio/77-roe.mp3",
    "definition": "fish eggs eaten as food",
    "zh": "鱼籽",
    "sentenceZh": "外面裹着一层很棒的鱼籽.",
    "sentence": "There's some very nice roe on the outside.",
    "match": "roe"
  },
  {
    "word": "fishy",
    "ipa": "/ˈfɪʃi/",
    "image": "assets/images/78-fishy.jpg",
    "imageAlt": "fishy",
    "audio": "assets/audio/78-fishy.mp3",
    "definition": "tasting or smelling of fish",
    "zh": "腥的",
    "sentenceZh": "吃多了会有点腥.",
    "sentence": "It can be a little bit fishy if you have a lot.",
    "match": "fishy"
  },
  {
    "word": "funnily enough",
    "ipa": "/ˈfʌnəli ɪˈnʌf/",
    "image": "assets/images/79-funnily-enough.jpg",
    "imageAlt": "funnily enough",
    "audio": "assets/audio/79-funnily-enough.mp3",
    "definition": "strangely or amusingly; used to introduce something surprising",
    "zh": "说来有趣",
    "sentenceZh": "有意思的是,这份摆盘的亮点居然是芥末.",
    "sentence": "The highlight, funnily enough, of this display here, is the wasabi.",
    "match": "funnily enough"
  },
  {
    "word": "wasabi",
    "ipa": "/wəˈsɑbi/",
    "image": "assets/images/80-wasabi.jpg",
    "imageAlt": "wasabi",
    "audio": "assets/audio/80-wasabi.mp3",
    "definition": "a hot green Japanese condiment",
    "zh": "芥末(山葵)",
    "sentenceZh": "有意思的是,这份摆盘的亮点居然是芥末.",
    "sentence": "The highlight, funnily enough, of this display here, is the wasabi.",
    "match": "wasabi"
  },
  {
    "word": "aquamarine",
    "ipa": "/ˌɑkwəmərˈin/",
    "image": "assets/images/81-aquamarine.jpg",
    "imageAlt": "aquamarine gemstone",
    "audio": "assets/audio/81-aquamarine.mp3",
    "definition": "a pale greenish-blue color, like clear seawater",
    "zh": "浅蓝绿色; 海蓝宝石色",
    "sentenceZh": "这里有一个可爱的小咖啡馆, 整体是蓝绿色的, 设计很漂亮, 和酒店其余部分截然不同, 离酒店其他地方也很远.",
    "sentence": "So this is an adorable, little cafe that they have here, that has an aquamarine teal color about it.",
    "match": "aquamarine"
  },
  {
    "word": "teal",
    "ipa": "/ˈtil/",
    "image": "assets/images/82-teal.jpg",
    "imageAlt": "teal duck feathers",
    "audio": "assets/audio/82-teal.mp3",
    "definition": "a dark bluish-green color",
    "zh": "深蓝绿色; 青绿色",
    "sentenceZh": "这里有一个可爱的小咖啡馆, 整体是蓝绿色的, 设计很漂亮, 和酒店其余部分截然不同, 离酒店其他地方也很远.",
    "sentence": "So this is an adorable, little cafe that they have here, that has an aquamarine teal color about it.",
    "match": "teal"
  },
  {
    "word": "sourdough",
    "ipa": "/ˈsaʊrˌdoʊ/",
    "image": "assets/images/83-sourdough.jpg",
    "imageAlt": "sourdough",
    "audio": "assets/audio/83-sourdough.mp3",
    "definition": "bread made with fermented dough, slightly sour",
    "zh": "酸面包",
    "sentenceZh": "菜单大部分围绕酸面包或芒果.",
    "sentence": "Most of it revolves around sourdough bread or mango.",
    "match": "sourdough"
  },
  {
    "word": "fizzy",
    "ipa": "/ˈfɪzi/",
    "image": "assets/images/84-fizzy.jpg",
    "imageAlt": "fizzy",
    "audio": "assets/audio/84-fizzy.mp3",
    "definition": "bubbly, carbonated",
    "zh": "带气泡的",
    "sentenceZh": "我点了最受欢迎的芒果气泡饮.",
    "sentence": "I ordered the most popular drink, which is their mango fizzy drink.",
    "match": "fizzy"
  },
  {
    "word": "porcelain",
    "ipa": "/ˈpɔrsəlɪn/",
    "image": "assets/images/85-porcelain.jpg",
    "imageAlt": "Chinese blue white porcelain vase",
    "audio": "assets/audio/85-porcelain.mp3",
    "definition": "a fine white ceramic material",
    "zh": "瓷器",
    "sentenceZh": "上面有只半岛酒店的小熊,是瓷器做的.",
    "sentence": "There's a little bear that's made out of porcelain with the Peninsula on top.",
    "match": "porcelain"
  },
  {
    "word": "wagyu",
    "ipa": "/ˈwɑɡju/",
    "image": "assets/images/86-wagyu.jpg",
    "imageAlt": "Japanese wagyu beef",
    "audio": "assets/audio/86-wagyu.mp3",
    "definition": "a breed of Japanese beef, richly marbled",
    "zh": "和牛",
    "sentenceZh": "我要试试菜单上最受欢迎的东西之一:和牛牛排.",
    "sentence": "I'm going to try one of the most popular things on the menu, their wagyu steak.",
    "match": "wagyu"
  },
  {
    "word": "garnish",
    "ipa": "/ˈɡɑrnɪʃ/",
    "image": "assets/images/87-garnish.jpg",
    "imageAlt": "garnish",
    "audio": "assets/audio/87-garnish.mp3",
    "definition": "a small decoration added to food",
    "zh": "装饰配料",
    "sentenceZh": "说真的,你连荷兰酱和任何装饰配料都不需要.",
    "sentence": "Honestly, you don't even need the béarnaise, or really, any of the garnish on here.",
    "match": "garnish"
  },
  {
    "word": "cannoli",
    "ipa": "/kəˈnoʊli/",
    "image": "assets/images/88-cannoli.jpg",
    "imageAlt": "cannoli",
    "audio": "assets/audio/88-cannoli.mp3",
    "definition": "an Italian pastry tube filled with sweet cream",
    "zh": "意式奶油卷",
    "sentenceZh": "乍看像小卷筒,其实是脆土豆.",
    "sentence": "Almost a little cannoli, but it's actually a crispy potato.",
    "match": "cannoli"
  },
  {
    "word": "crunchy",
    "ipa": "/ˈkrʌntʃi/",
    "image": "assets/images/89-crunchy.jpg",
    "imageAlt": "crunchy",
    "audio": "assets/audio/89-crunchy.mp3",
    "definition": "making a crisp sound when bitten",
    "zh": "酥脆的",
    "sentenceZh": "外脆内软,风味十足.",
    "sentence": "Very crunchy, soft, flavorful inside.",
    "match": "crunchy"
  },
  {
    "word": "flavorful",
    "ipa": "/ˈfleɪvərfəl/",
    "image": "assets/images/90-flavorful.jpg",
    "imageAlt": "flavorful",
    "audio": "assets/audio/90-flavorful.mp3",
    "definition": "full of flavor",
    "zh": "风味浓郁的",
    "sentenceZh": "外脆内软,风味十足.",
    "sentence": "Very crunchy, soft, flavorful inside.",
    "match": "flavorful"
  },
  {
    "word": "cozy",
    "ipa": "/ˈkoʊzi/",
    "image": "assets/images/91-cozy.jpg",
    "imageAlt": "cozy",
    "audio": "assets/audio/91-cozy.mp3",
    "definition": "warm, comfortable and intimate",
    "zh": "温馨舒适的",
    "sentenceZh": "这里确实像一座温馨的传统瑞士木屋.",
    "sentence": "It definitely feels like a cozy, traditional Swiss chalet in here.",
    "match": "cozy"
  },
  {
    "word": "chalet",
    "ipa": "/ˈʃæˌleɪ/",
    "image": "assets/images/92-chalet.jpg",
    "imageAlt": "chalet",
    "audio": "assets/audio/92-chalet.mp3",
    "definition": "a Swiss-style wooden house",
    "zh": "瑞士木屋",
    "sentenceZh": "这里确实像一座温馨的传统瑞士木屋.",
    "sentence": "It definitely feels like a cozy, traditional Swiss chalet in here.",
    "match": "chalet"
  },
  {
    "word": "raclette",
    "ipa": "/rəˈklɛt/",
    "image": "assets/images/93-raclette.jpg",
    "imageAlt": "raclette melted cheese",
    "audio": "assets/audio/93-raclette.mp3",
    "definition": "a Swiss dish of melted cheese scraped over food",
    "zh": "拉克莱特(熔岩芝士)",
    "sentenceZh": "这是他们的两道招牌菜之一:拉克莱特,一种上面铺土豆的芝士.",
    "sentence": "So this is one of their two most famous dishes here: this is the raclette, which is a type of cheese that has potato on top.",
    "match": "raclette"
  },
  {
    "word": "fondue",
    "ipa": "/fɑnˈdu/",
    "image": "assets/images/94-fondue.jpg",
    "imageAlt": "Swiss cheese fondue pot",
    "audio": "assets/audio/94-fondue.mp3",
    "definition": "a pot of melted cheese for dipping",
    "zh": "芝士火锅",
    "sentenceZh": "主角来了--芝士火锅,还配了几样有趣的小菜.",
    "sentence": "So here we have it, the star of the show. This is the cheese fondue, the main course here, and they come out with a couple of interesting sides, which I'm a little shocked about.",
    "match": "fondue"
  },
  {
    "word": "macaroni",
    "ipa": "/ˌmækəˈroʊni/",
    "image": "assets/images/95-macaroni.jpg",
    "imageAlt": "macaroni",
    "audio": "assets/audio/95-macaroni.mp3",
    "definition": "short curved pasta tubes",
    "zh": "通心粉",
    "sentenceZh": "这就是煮好的通心粉.",
    "sentence": "So this is just cooked macaroni.",
    "match": "macaroni"
  },
  {
    "word": "undertones",
    "ipa": "/ˈʌndərˌtoʊnz/",
    "image": "assets/images/96-undertones.jpg",
    "imageAlt": "coffee tasting aroma notes",
    "audio": "assets/audio/96-undertones.mp3",
    "definition": "subtle secondary flavors or qualities",
    "zh": "底味,弦外之音",
    "sentenceZh": "能尝到一点培根味,但火锅的味道还有很多层次.",
    "sentence": "Significantly different flavor than I expected. You can taste a little bit of the bacon, but there's a lot of undertones to the flavor of the fondue.",
    "match": "undertones"
  },
  {
    "word": "pistachio",
    "ipa": "/pəˈstæʃiˌoʊ/",
    "image": "assets/images/97-pistachio.jpg",
    "imageAlt": "pistachio",
    "audio": "assets/audio/97-pistachio.mp3",
    "definition": "a green nut",
    "zh": "开心果",
    "sentenceZh": "巧克力小房子,四周铺着开心果碎当草地.",
    "sentence": "A little house made out of chocolate with a pistachio base around it to look like grass.",
    "match": "pistachio"
  },
  {
    "word": "drizzle",
    "ipa": "/ˈdrɪzəl/",
    "image": "assets/images/98-drizzle.jpg",
    "imageAlt": "drizzle",
    "audio": "assets/audio/98-drizzle.mp3",
    "definition": "to pour a thin stream of liquid over food",
    "zh": "淋,浇",
    "sentenceZh": "配的巧克力酱淋在房子上.",
    "sentence": "They give you chocolate sauce that you drizzle on top of the house.",
    "match": "drizzle"
  },
  {
    "word": "futuristic",
    "ipa": "/ˌfjutʃərˈɪstɪk/",
    "image": "assets/images/99-futuristic.jpg",
    "imageAlt": "futuristic architecture interior",
    "audio": "assets/audio/99-futuristic.mp3",
    "definition": "very modern, like from the future",
    "zh": "未来感的",
    "sentenceZh": "这家餐厅让我感觉像穿越到了一个未来主义的现代餐吧.",
    "sentence": "We are still in the Peninsula Hotel, mind you, and this restaurant feels like I have completely been transported to a futuristic, modern restaurant and bar.",
    "match": "futuristic"
  },
  {
    "word": "pianist",
    "ipa": "/ˈpiənɪst/",
    "image": "assets/images/100-pianist.jpg",
    "imageAlt": "pianist",
    "audio": "assets/audio/100-pianist.mp3",
    "definition": "a person who plays the piano",
    "zh": "钢琴师",
    "sentenceZh": "每晚都有现场音乐,包括钢琴师.",
    "sentence": "They have live music every single night, including a pianist.",
    "match": "pianist"
  },
  {
    "word": "culinary",
    "ipa": "/ˈkʌləˌnɛri/",
    "image": "assets/images/101-culinary.jpg",
    "imageAlt": "professional chef culinary cooking",
    "audio": "assets/audio/101-culinary.mp3",
    "definition": "relating to cooking or the kitchen",
    "zh": "烹饪的",
    "sentenceZh": "半岛的这顿晚餐展现了令人惊叹,多样化的烹饪艺术.",
    "sentence": "Whew, that was a lot of dining here at the Peninsula, an incredibly impressive, diverse display of culinary art in all of the different restaurants here.",
    "match": "culinary"
  },
  {
    "word": "critique",
    "ipa": "/krɪˈtik/",
    "image": "assets/images/102-critique.jpg",
    "imageAlt": "critique",
    "audio": "assets/audio/102-critique.mp3",
    "definition": "a detailed judgment or criticism",
    "zh": "批评意见",
    "sentenceZh": "我唯一的批评是并非每道菜都惊艳.",
    "sentence": "My only critique is that not every dish was extraordinary.",
    "match": "critique"
  },
  {
    "word": "plating",
    "ipa": "/ˈpleɪtɪŋ/",
    "image": "assets/images/103-plating.jpg",
    "imageAlt": "plating",
    "audio": "assets/audio/103-plating.mp3",
    "definition": "the arrangement of food on a plate",
    "zh": "摆盘",
    "sentenceZh": "摆盘,呈现,服务,样样都是顶级水准.",
    "sentence": "You saw the plating, the presentation, the serving, everything was top notch.",
    "match": "plating"
  },
  {
    "word": "top notch",
    "ipa": "/ˌtɑp ˈnɑtʃ/",
    "image": "assets/images/104-top-notch.jpg",
    "imageAlt": "top notch",
    "audio": "assets/audio/104-top-notch.mp3",
    "definition": "of the highest quality",
    "zh": "顶级的",
    "sentenceZh": "摆盘,呈现,服务,样样都是顶级水准.",
    "sentence": "You saw the plating, the presentation, the serving, everything was top notch.",
    "match": "top notch"
  },
  {
    "word": "minimalistic",
    "ipa": "/ˌmɪnəməˈlɪstɪk/",
    "image": "assets/images/105-minimalistic.jpg",
    "imageAlt": "minimalistic",
    "audio": "assets/audio/105-minimalistic.mp3",
    "definition": "very simple in design, with no extras",
    "zh": "极简的",
    "sentenceZh": "它看起来开胃又极简.",
    "sentence": "It is looking very appetizing, minimalistic.",
    "match": "minimalistic"
  },
  {
    "word": "zucchini",
    "ipa": "/zuˈkini/",
    "image": "assets/images/106-zucchini.jpg",
    "imageAlt": "zucchini",
    "audio": "assets/audio/106-zucchini.mp3",
    "definition": "a green summer squash (UK: courgette)",
    "zh": "西葫芦",
    "sentenceZh": "里面有西葫芦和另一种瓜.",
    "sentence": "It has a zucchini and another kind of squash here.",
    "match": "zucchini"
  },
  {
    "word": "silverware",
    "ipa": "/ˈsɪlvərˌwɛr/",
    "image": "assets/images/107-silverware.jpg",
    "imageAlt": "silverware",
    "audio": "assets/audio/107-silverware.mp3",
    "definition": "knives, forks and spoons; cutlery",
    "zh": "银餐具,刀叉",
    "sentenceZh": "半岛每天要使用超过两万件银器餐具.",
    "sentence": "They use over 20,000 pieces of silverware every single day here at The Peninsula.",
    "match": "silverware"
  },
  {
    "word": "accommodating",
    "ipa": "/əˈkɑməˌdeɪtɪŋ/",
    "image": "assets/images/108-accommodating.jpg",
    "imageAlt": "hotel concierge helping guest",
    "audio": "assets/audio/108-accommodating.mp3",
    "definition": "willing to help and meet requests",
    "zh": "乐于通融的",
    "sentenceZh": "服务测试环节:我打电话给前台,提一个他们通常不会照办的奇怪要求.",
    "sentence": "Now, the Service Test is the part of the review where I call the front desk and ask for something a little bit strange that they're not used to accommodating.",
    "match": "accommodating"
  },
  {
    "word": "chocolatier",
    "ipa": "/ˌtʃɑkələˈtɪr/",
    "image": "assets/images/109-chocolatier.jpg",
    "imageAlt": "chocolatier",
    "audio": "assets/audio/109-chocolatier.mp3",
    "definition": "a person or shop that makes fine chocolate",
    "zh": "巧克力师,巧克力工坊",
    "sentenceZh": "你没见到的是首席巧克力师,他号称半岛的威利·旺卡,能用巧克力做出任何东西.",
    "sentence": "Who you didn't meet is the head chocolatier, who is really the Willy Wonka of the Peninsula.",
    "match": "chocolatier"
  },
  {
    "word": "surcharge",
    "ipa": "/ˈsɜrˌtʃɑrdʒ/",
    "image": "assets/images/110-surcharge.jpg",
    "imageAlt": "credit card surcharge receipt",
    "audio": "assets/audio/110-surcharge.mp3",
    "definition": "an extra fee added on top",
    "zh": "附加费",
    "sentenceZh": "一位员工主动去商店帮我买了需要的东西,按原价记账,没有任何附加费.",
    "sentence": "One of the staff offered to go all the way to the store and pick up the thing that I needed and just bill it to the room at the exact price with no surcharge or anything extra.",
    "match": "surcharge"
  },
  {
    "word": "attentive",
    "ipa": "/əˈtɛntɪv/",
    "image": "assets/images/111-attentive.jpg",
    "imageAlt": "attentive waiter fine dining service",
    "audio": "assets/audio/111-attentive.mp3",
    "definition": "careful and considerate in serving",
    "zh": "殷勤周到的",
    "sentenceZh": "酒店各处,他们总是格外殷勤,乐于助人.",
    "sentence": "Generally around the hotel, they were always extraordinarily attentive, supportive, helpful, and they were overstaffed everywhere, which was a really nice touch.",
    "match": "attentive"
  },
  {
    "word": "overstaffed",
    "ipa": "/ˌoʊvərˈstæft/",
    "image": "assets/images/112-overstaffed.jpg",
    "imageAlt": "overstaffed",
    "audio": "assets/audio/112-overstaffed.mp3",
    "definition": "having more staff than needed",
    "zh": "服务人员充足的",
    "sentenceZh": "酒店各处人手都很充足,这一点很加分.",
    "sentence": "They were overstaffed everywhere, which was a really nice touch.",
    "match": "overstaffed"
  },
  {
    "word": "sparse",
    "ipa": "/ˈspɑrs/",
    "image": "assets/images/113-sparse.jpg",
    "imageAlt": "sparse",
    "audio": "assets/audio/113-sparse.mp3",
    "definition": "thinly spread; few and far between",
    "zh": "稀少的",
    "sentenceZh": "日历上的活动安排相当稀少.",
    "sentence": "They are pretty sparse in the calendar.",
    "match": "sparse"
  },
  {
    "word": "plush",
    "ipa": "/ˈplʌʃ/",
    "image": "assets/images/114-plush.jpg",
    "imageAlt": "plush velvet hotel chair",
    "audio": "assets/audio/114-plush.mp3",
    "definition": "soft, thick and luxurious",
    "zh": "柔软豪华的",
    "sentenceZh": "这辆劳斯莱斯后排座椅舒服极了,脚下还有非常柔软的地毯.",
    "sentence": "One other fun thing about this Rolls Royce is the seats back here are not only incredibly comfortable, I mean, there's a very plush carpet underneath my shoes.",
    "match": "plush"
  },
  {
    "word": "caliber",
    "ipa": "/ˈkæləbər/",
    "image": "assets/images/115-caliber.jpg",
    "imageAlt": "caliber",
    "audio": "assets/audio/115-caliber.mp3",
    "definition": "the level of quality or ability",
    "zh": "水准,档次",
    "sentenceZh": "酒店用车是这个档次,而且有这么多辆.",
    "sentence": "The house car is this caliber and they have this many of them.",
    "match": "caliber"
  },
  {
    "word": "facade",
    "ipa": "/fəˈsɑd/",
    "image": "assets/images/116-facade.jpg",
    "imageAlt": "ornate building facade",
    "audio": "assets/audio/116-facade.mp3",
    "definition": "the front face of a building",
    "zh": "建筑立面",
    "sentenceZh": "你没看到的还包括:这座建筑的外立面一年四季都在变化.",
    "sentence": "Now for the It-Factor. Some of the things that you didn't see at this hotel include the facade of the building actually changing throughout the year.",
    "match": "facade"
  },
  {
    "word": "ribbon",
    "ipa": "/ˈrɪbən/",
    "image": "assets/images/117-ribbon.jpg",
    "imageAlt": "ribbon",
    "audio": "assets/audio/117-ribbon.mp3",
    "definition": "a long narrow strip of fabric used for decoration",
    "zh": "丝带",
    "sentenceZh": "节日期间他们会用蓝丝带装点楼面.",
    "sentence": "They wrap the front in this blue ribbon.",
    "match": "ribbon"
  },
  {
    "word": "lantern",
    "ipa": "/ˈlæntərn/",
    "image": "assets/images/118-lantern.jpg",
    "imageAlt": "lantern",
    "audio": "assets/audio/118-lantern.mp3",
    "definition": "a light with a protective case, often decorative",
    "zh": "灯笼",
    "sentenceZh": "春节期间则挂满红灯笼.",
    "sentence": "During Chinese New Year, it's red lanterns.",
    "match": "lanterns"
  },
  {
    "word": "gravitas",
    "ipa": "/ˈɡrævɪˌtɑs/",
    "image": "assets/images/119-gravitas.jpg",
    "imageAlt": "distinguished formal speaker portrait",
    "audio": "assets/audio/119-gravitas.mp3",
    "definition": "seriousness, dignity and weight of presence",
    "zh": "庄重气场",
    "sentenceZh": "总的来说,住在这里你真的会有强烈的场所感--它在香港这座城市里很有气场和分量.",
    "sentence": "Generally speaking, you really do have a sense of place when you're staying here. It has a lot of gravitas and power here in the city of Hong Kong.",
    "match": "gravitas"
  }
];
