window.VOCABULARY_CARDS = [
  {
    "word": "carat",
    "ipa": "/ˈkɛrət/",
    "image": "assets/images/01-carat.jpg",
    "imageAlt": "carat",
    "audio": "assets/audio/01-carat.mp3",
    "definition": "a unit of weight for gemstones",
    "zh": "克拉",
    "sentenceZh": "这是一颗钻石,580克拉,而且是他们在这台机器里种出来的.",
    "sentence": "This is a diamond, a 580 carat diamond, and they grew it inside this machine.",
    "match": "carat"
  },
  {
    "word": "recreate",
    "ipa": "/ˈrɛkriˌeɪt/",
    "image": "assets/images/02-recreate.jpg",
    "imageAlt": "recreate",
    "audio": "assets/audio/02-recreate.mp3",
    "definition": "to create again or imitate",
    "zh": "重现,再造",
    "sentenceZh": "他们造出巨型机器,在实验室里重现地球内部环境来培育钻石.",
    "sentence": "They've built giant machines that can recreate the inside of the earth to grow diamonds.",
    "match": "recreate"
  },
  {
    "word": "unlock",
    "ipa": "/ənˈlɑk/",
    "image": "assets/images/03-unlock.jpg",
    "imageAlt": "unlock",
    "audio": "assets/audio/03-unlock.mp3",
    "definition": "to release or make available",
    "zh": "解锁,释放",
    "sentenceZh": "它正在释放这种超级材料不为人知的潜力.",
    "sentence": "It's now unlocking the hidden potential of what turns out to be an incredible super material.",
    "match": "unlocking"
  },
  {
    "word": "turn out",
    "ipa": "/tɜrn aʊt/",
    "image": "assets/images/04-turn-out.jpg",
    "imageAlt": "turn out",
    "audio": "assets/audio/04-turn-out.mp3",
    "definition": "to prove to be; to result",
    "zh": "结果证明,原来是",
    "sentenceZh": "它正释放出这种材料的隐藏潜力--结果证明这是种惊人的超级材料.",
    "sentence": "It's now unlocking the hidden potential of what turns out to be an incredible super material.",
    "match": "turns out"
  },
  {
    "word": "shrink",
    "ipa": "/ˈʃrɪŋk/",
    "image": "assets/images/05-shrink.jpg",
    "imageAlt": "shrink",
    "audio": "assets/audio/05-shrink.mp3",
    "definition": "to become smaller",
    "zh": "缩小",
    "sentenceZh": "我们把视角缩小钻进电脑里,给你看看钻石为什么不是你想的那样.",
    "sentence": "We're shrinking down inside a computer to show you why diamonds are not what you think.",
    "match": "shrinking"
  },
  {
    "word": "fistful",
    "ipa": "/ˈfɪstfʊl/",
    "image": "assets/images/06-fistful.png",
    "imageAlt": "fistful",
    "audio": "assets/audio/06-fistful.mp3",
    "definition": "as much as a hand can hold",
    "zh": "一把(的量)",
    "sentenceZh": "容我失陪一下,先抓满一把钻石.",
    "sentence": "Excuse me while I just hold a fistful of diamonds.",
    "match": "fistful"
  },
  {
    "word": "gemstone",
    "ipa": "/ˈdʒɛmˌstoʊn/",
    "image": "assets/images/07-gemstone.jpg",
    "imageAlt": "gemstone",
    "audio": "assets/audio/07-gemstone.mp3",
    "definition": "a precious stone used in jewelry",
    "zh": "宝石",
    "sentenceZh": "大多数宝石--祖母绿,蓝宝石,红宝石--都形成于地壳.",
    "sentence": "Most other gemstones, emeralds and sapphires and rubies, form here in the crust.",
    "match": "gemstones"
  },
  {
    "word": "emerald",
    "ipa": "/ˈɛmərəld/",
    "image": "assets/images/08-emerald.jpg",
    "imageAlt": "emerald",
    "audio": "assets/audio/08-emerald.mp3",
    "definition": "a green precious stone",
    "zh": "祖母绿",
    "sentenceZh": "大多数宝石--祖母绿,蓝宝石,红宝石--都形成于地壳.",
    "sentence": "Most other gemstones, emeralds and sapphires and rubies, form here in the crust.",
    "match": "emeralds"
  },
  {
    "word": "sapphire",
    "ipa": "/ˈsæfaɪr/",
    "image": "assets/images/09-sapphire.jpg",
    "imageAlt": "sapphire",
    "audio": "assets/audio/09-sapphire.mp3",
    "definition": "a blue precious stone",
    "zh": "蓝宝石",
    "sentenceZh": "大多数宝石--祖母绿,蓝宝石,红宝石--都形成于地壳.",
    "sentence": "Most other gemstones, emeralds and sapphires and rubies, form here in the crust.",
    "match": "sapphires"
  },
  {
    "word": "ruby",
    "ipa": "/ˈrubi/",
    "image": "assets/images/10-ruby.jpg",
    "imageAlt": "ruby",
    "audio": "assets/audio/10-ruby.mp3",
    "definition": "a red precious stone",
    "zh": "红宝石",
    "sentenceZh": "大多数宝石--祖母绿,蓝宝石,红宝石--都形成于地壳.",
    "sentence": "Most other gemstones, emeralds and sapphires and rubies, form here in the crust.",
    "match": "rubies"
  },
  {
    "word": "crust",
    "ipa": "/ˈkrʌst/",
    "image": "assets/images/11-crust.jpg",
    "imageAlt": "crust",
    "audio": "assets/audio/11-crust.mp3",
    "definition": "the hard outer layer of the Earth",
    "zh": "地壳",
    "sentenceZh": "大多数宝石--祖母绿,蓝宝石,红宝石--都形成于地壳.",
    "sentence": "Most other gemstones, emeralds and sapphires and rubies, form here in the crust.",
    "match": "crust"
  },
  {
    "word": "mantle",
    "ipa": "/ˈmæntəl/",
    "image": "assets/images/12-mantle.jpg",
    "imageAlt": "mantle",
    "audio": "assets/audio/12-mantle.mp3",
    "definition": "the hot layer of the Earth below the crust",
    "zh": "地幔",
    "sentenceZh": "但钻石来自这里--地幔内部.",
    "sentence": "But diamonds... come from here inside the mantle.",
    "match": "mantle"
  },
  {
    "word": "goopy",
    "ipa": "/ˈɡupi/",
    "image": "assets/images/13-goopy.jpg",
    "imageAlt": "goopy",
    "audio": "assets/audio/13-goopy.mp3",
    "definition": "thick and sticky",
    "zh": "黏稠的",
    "sentenceZh": "这种极热,黏稠的液态岩石里充满了钻石的原料.",
    "sentence": "This extremely hot, goopy liquid rock is filled with everything needed to make diamonds.",
    "match": "goopy"
  },
  {
    "word": "grind",
    "ipa": "/ˈɡraɪnd/",
    "image": "assets/images/14-grind.jpg",
    "imageAlt": "grind",
    "audio": "assets/audio/14-grind.mp3",
    "definition": "to crush into powder or rub away",
    "zh": "磨,碾",
    "sentenceZh": "几十年来我们用钻石切割,钻孔,打磨,抛光,因为它无坚不摧.",
    "sentence": "We've been using diamond for decades to cut and drill and grind and polish because diamond can cut anything.",
    "match": "grind"
  },
  {
    "word": "polish",
    "ipa": "/ˈpɑlɪʃ/",
    "image": "assets/images/15-polish.jpg",
    "imageAlt": "polish",
    "audio": "assets/audio/15-polish.mp3",
    "definition": "to rub until smooth and shiny",
    "zh": "抛光",
    "sentenceZh": "几十年来我们用钻石切割,钻孔,打磨,抛光,因为它无坚不摧.",
    "sentence": "We've been using diamond for decades to cut and drill and grind and polish because diamond can cut anything.",
    "match": "polish"
  },
  {
    "word": "gem",
    "ipa": "/ˈdʒɛm/",
    "image": "assets/images/16-gem.png",
    "imageAlt": "gem",
    "audio": "assets/audio/16-gem.mp3",
    "definition": "a precious stone, especially when cut",
    "zh": "宝石",
    "sentenceZh": "那是我们的腔室里长出来的, 几周的时间里那颗小种子变成了大原石, 最终可能切出两三克拉的这颗宝石.",
    "sentence": "So that's grown in our chambers and over several weeks of time that little seed is converted into that big rough and that might end up being two or three carat in this gem.",
    "match": "gem"
  },
  {
    "word": "fragment",
    "ipa": "/ˈfræɡmənt/",
    "image": "assets/images/17-fragment.jpg",
    "imageAlt": "fragment",
    "audio": "assets/audio/17-fragment.mp3",
    "definition": "a small broken piece",
    "zh": "碎片",
    "sentenceZh": "他们把我手上的小碎屑吹掉,免得嵌进皮肤.",
    "sentence": "They blow these little fragments off of my hand so they don't get embedded in my skin.",
    "match": "fragments"
  },
  {
    "word": "embedded",
    "ipa": "/ɛmˈbɛdɪd/",
    "image": "assets/images/18-embedded.jpg",
    "imageAlt": "embedded",
    "audio": "assets/audio/18-embedded.mp3",
    "definition": "fixed firmly inside something",
    "zh": "嵌入的",
    "sentenceZh": "他们把我手上的小碎屑吹掉,免得嵌进皮肤.",
    "sentence": "They blow these little fragments off of my hand so they don't get embedded in my skin.",
    "match": "embedded"
  },
  {
    "word": "diamonditis",
    "ipa": "/ˌdaɪəməndˈaɪtəs/",
    "image": "assets/images/19-diamonditis.jpg",
    "imageAlt": "diamonditis",
    "audio": "assets/audio/19-diamonditis.mp3",
    "definition": "a made-up word for being obsessed with diamonds (diamond + -itis)",
    "zh": "钻石瘾(生造词:diamond + -itis)",
    "sentenceZh": "我得了\"钻石炎\".",
    "sentence": "I've got diamonditis.",
    "match": "diamonditis"
  },
  {
    "word": "polycrystalline",
    "ipa": "/ˌpɑliˈkrɪstələn/",
    "image": "assets/images/20-polycrystalline.jpg",
    "imageAlt": "polycrystalline",
    "audio": "assets/audio/20-polycrystalline.mp3",
    "definition": "made of many small crystals",
    "zh": "多晶的",
    "sentenceZh": "他们不种单一大晶体,而是长出数百万微小晶粒--多晶金刚石.",
    "sentence": "Instead of growing one single crystal, they grow millions of tiny diamond grains, a polycrystalline diamond.",
    "match": "polycrystalline"
  },
  {
    "word": "superpower",
    "ipa": "/ˈsupərˌpaʊər/",
    "image": "assets/images/21-superpower.jpg",
    "imageAlt": "superpower",
    "audio": "assets/audio/21-superpower.mp3",
    "definition": "an extraordinary special ability",
    "zh": "超能力",
    "sentenceZh": "这是钻石一个大多数人都不知道的隐藏超能力.",
    "sentence": "A hidden superpower of diamond that most people don't know about.",
    "match": "superpower"
  },
  {
    "word": "stiff",
    "ipa": "/ˈstɪf/",
    "image": "assets/images/22-stiff.jpg",
    "imageAlt": "stiff",
    "audio": "assets/audio/22-stiff.mp3",
    "definition": "rigid, not easily bent",
    "zh": "坚硬的,刚性的",
    "sentenceZh": "钻石内部的键又短又硬,但原子依然会振动.",
    "sentence": "The bonds inside a diamond are short and stiff, but the atoms can still vibrate.",
    "match": "stiff"
  },
  {
    "word": "vibrate",
    "ipa": "/ˈvaɪbreɪt/",
    "image": "assets/images/23-vibrate.jpg",
    "imageAlt": "vibrate",
    "audio": "assets/audio/23-vibrate.mp3",
    "definition": "to move rapidly back and forth",
    "zh": "振动",
    "sentenceZh": "钻石内部的键又短又硬,但原子依然会振动.",
    "sentence": "The bonds inside a diamond are short and stiff, but the atoms can still vibrate.",
    "match": "vibrate"
  },
  {
    "word": "jostle",
    "ipa": "/ˈdʒɑsəl/",
    "image": "assets/images/24-jostle.jpg",
    "imageAlt": "jostle",
    "audio": "assets/audio/24-jostle.mp3",
    "definition": "to push or bump roughly",
    "zh": "推挤",
    "sentenceZh": "一个原子推挤相邻的原子,再传导给下一个,波动就传遍晶体.",
    "sentence": "When one atom jostles its neighbor and that one jostles the next, the ripple travels through the crystal.",
    "match": "jostles"
  },
  {
    "word": "ripple",
    "ipa": "/ˈrɪpəl/",
    "image": "assets/images/25-ripple.jpg",
    "imageAlt": "ripple",
    "audio": "assets/audio/25-ripple.mp3",
    "definition": "a small wave or spreading effect",
    "zh": "涟漪,波动",
    "sentenceZh": "一个原子推挤相邻的原子,再传导给下一个,波动就传遍晶体.",
    "sentence": "When one atom jostles its neighbor and that one jostles the next, the ripple travels through the crystal.",
    "match": "ripple"
  },
  {
    "word": "conductivity",
    "ipa": "/ˌkɑndʌkˈtɪvəti/",
    "image": "assets/images/26-conductivity.jpg",
    "imageAlt": "conductivity",
    "audio": "assets/audio/26-conductivity.mp3",
    "definition": "the ability to conduct heat or electricity",
    "zh": "传导率",
    "sentenceZh": "这叫做它的导热率.",
    "sentence": "It's called its thermal conductivity.",
    "match": "conductivity"
  },
  {
    "word": "backbone",
    "ipa": "/ˈbækˌboʊn/",
    "image": "assets/images/27-backbone.jpg",
    "imageAlt": "backbone",
    "audio": "assets/audio/27-backbone.mp3",
    "definition": "the main support or foundation",
    "zh": "脊梁,支柱",
    "sentenceZh": "硅是计算世界的脊梁.",
    "sentence": "Silicon is the backbone of computing.",
    "match": "backbone"
  },
  {
    "word": "transistor",
    "ipa": "/trænˈzɪstər/",
    "image": "assets/images/28-transistor.png",
    "imageAlt": "transistor",
    "audio": "assets/audio/28-transistor.mp3",
    "definition": "a tiny electronic switch in microchips",
    "zh": "晶体管",
    "sentenceZh": "晶体管--越多晶体管,算力越强.",
    "sentence": "Transistors. More transistors, more processing power.",
    "match": "Transistors"
  },
  {
    "word": "millimeter",
    "ipa": "/ˈmɪləˌmitər/",
    "image": "assets/images/29-millimeter.png",
    "imageAlt": "millimeter",
    "audio": "assets/audio/29-millimeter.mp3",
    "definition": "one thousandth of a meter",
    "zh": "毫米",
    "sentenceZh": "这是最小的蚂蚁物种,只有 1 毫米.",
    "sentence": "This is the smallest species of ant. It's only 1 millimeter.",
    "match": "millimeter"
  },
  {
    "word": "tardigrade",
    "ipa": "/ˈtɑrdəˌɡreɪd/",
    "image": "assets/images/30-tardigrade.jpg",
    "imageAlt": "tardigrade",
    "audio": "assets/audio/30-tardigrade.mp3",
    "definition": "a tiny eight-legged animal that survives extreme conditions",
    "zh": "水熊虫",
    "sentenceZh": "这是我最喜欢的动物之一--水熊虫.",
    "sentence": "This is one of my favorite animals, the tardigrade.",
    "match": "tardigrade"
  },
  {
    "word": "cram",
    "ipa": "/ˈkræm/",
    "image": "assets/images/31-cram.jpg",
    "imageAlt": "cram",
    "audio": "assets/audio/31-cram.mp3",
    "definition": "to force too much into a small space",
    "zh": "硬塞,挤满",
    "sentenceZh": "他们不再平铺,而是像把更多房子塞进社区一样,开始把它们叠起来.",
    "sentence": "Instead of putting them side by side, like cramming more houses into a neighborhood, they've started stacking them.",
    "match": "cramming"
  },
  {
    "word": "stack",
    "ipa": "/ˈstæk/",
    "image": "assets/images/32-stack.jpg",
    "imageAlt": "stack",
    "audio": "assets/audio/32-stack.mp3",
    "definition": "to pile on top of each other",
    "zh": "堆叠",
    "sentenceZh": "他们不再平铺,而是像把更多房子塞进社区一样,开始把它们叠起来.",
    "sentence": "Instead of putting them side by side, like cramming more houses into a neighborhood, they've started stacking them.",
    "match": "stacking"
  },
  {
    "word": "humongous",
    "ipa": "/hjuˈmʌŋɡəs/",
    "image": "assets/images/33-humongous.jpg",
    "imageAlt": "humongous",
    "audio": "assets/audio/33-humongous.mp3",
    "definition": "extremely large",
    "zh": "巨大的",
    "sentenceZh": "这一切给电子元件带来巨大的压力.",
    "sentence": "All of that is exercising a humongous pressure on the electronics.",
    "match": "humongous"
  },
  {
    "word": "compel",
    "ipa": "/kəmˈpɛl/",
    "image": "assets/images/34-compel.jpg",
    "imageAlt": "compel",
    "audio": "assets/audio/34-compel.mp3",
    "definition": "to force or drive",
    "zh": "迫使",
    "sentenceZh": "它们越小,你越逼它们跑得更快更猛,产生的热量就越多.",
    "sentence": "The smaller they get and the more you compel them to run faster and harder, the more heat you are generating.",
    "match": "compel"
  },
  {
    "word": "fin",
    "ipa": "/ˈfɪn/",
    "image": "assets/images/35-fin.jpg",
    "imageAlt": "fin",
    "audio": "assets/audio/35-fin.mp3",
    "definition": "a thin projecting part used for cooling",
    "zh": "鳍片",
    "sentenceZh": "他们把液体泵过管道,再导入一堆铝制散热鳍片.",
    "sentence": "They pump liquid through pipes and dump it into a bunch of aluminum fins.",
    "match": "fins"
  },
  {
    "word": "satellite",
    "ipa": "/ˈsætəˌlaɪt/",
    "image": "assets/images/36-satellite.png",
    "imageAlt": "satellite",
    "audio": "assets/audio/36-satellite.mp3",
    "definition": "a device orbiting the Earth",
    "zh": "卫星",
    "sentenceZh": "在电脑里是小问题,在数据中心,电动车和卫星上就是大问题.",
    "sentence": "It's a small problem in your computer, but a really big problem in data centers and electric cars and satellites.",
    "match": "satellites"
  },
  {
    "word": "thermally",
    "ipa": "/ˈθɜrməli/",
    "image": "assets/images/37-thermally.jpg",
    "imageAlt": "thermally",
    "audio": "assets/audio/37-thermally.mp3",
    "definition": "in relation to heat",
    "zh": "热学上",
    "sentenceZh": "但如果能用导热性更强的材料呢?比如钻石.",
    "sentence": "But what if we could use an even more thermally conductive material, like diamonds?",
    "match": "thermally"
  },
  {
    "word": "conductive",
    "ipa": "/kənˈdʌktɪv/",
    "image": "assets/images/38-conductive.jpg",
    "imageAlt": "conductive",
    "audio": "assets/audio/38-conductive.mp3",
    "definition": "able to transmit heat or electricity",
    "zh": "导(热/电)的",
    "sentenceZh": "但如果能用导热性更强的材料呢?比如钻石.",
    "sentence": "But what if we could use an even more thermally conductive material, like diamonds?",
    "match": "conductive"
  },
  {
    "word": "polarized",
    "ipa": "/ˈpoʊləˌraɪzd/",
    "image": "assets/images/39-polarized.png",
    "imageAlt": "polarized",
    "audio": "assets/audio/39-polarized.mp3",
    "definition": "filtering light waves in one direction",
    "zh": "偏光的",
    "sentenceZh": "它就像偏光太阳镜,只是给电脑用的.",
    "sentence": "It's like polarized sunglasses, but for your computer.",
    "match": "polarized"
  },
  {
    "word": "molecule",
    "ipa": "/ˈmɑləˌkjul/",
    "image": "assets/images/40-molecule.jpg",
    "imageAlt": "molecule",
    "audio": "assets/audio/40-molecule.mp3",
    "definition": "a group of atoms bonded together",
    "zh": "分子",
    "sentenceZh": "按下按钮,额外电压让那一层里的分子发生倾斜.",
    "sentence": "When I click this button, extra voltage causes the molecules in that layer to tilt.",
    "match": "molecules"
  },
  {
    "word": "voltage",
    "ipa": "/ˈvoʊltədʒ/",
    "image": "assets/images/41-voltage.jpg",
    "imageAlt": "voltage",
    "audio": "assets/audio/41-voltage.mp3",
    "definition": "electrical pressure, measured in volts",
    "zh": "电压",
    "sentenceZh": "按下按钮,额外电压让分子倾斜.",
    "sentence": "When I click this button, extra voltage causes the molecules in that layer to tilt.",
    "match": "voltage"
  },
  {
    "word": "tilt",
    "ipa": "/ˈtɪlt/",
    "image": "assets/images/42-tilt.jpg",
    "imageAlt": "tilt",
    "audio": "assets/audio/42-tilt.mp3",
    "definition": "to lean or angle",
    "zh": "倾斜",
    "sentenceZh": "按下按钮,额外电压让那一层里的分子发生倾斜.",
    "sentence": "When I click this button, extra voltage causes the molecules in that layer to tilt.",
    "match": "tilt"
  },
  {
    "word": "nosy",
    "ipa": "/ˈnoʊzi/",
    "image": "assets/images/43-nosy.jpg",
    "imageAlt": "nosy",
    "audio": "assets/audio/43-nosy.mp3",
    "definition": "too interested in other people's business",
    "zh": "爱打听的,偷看的",
    "sentenceZh": "斜射向旁边那个爱偷看的人的光则通不过.",
    "sentence": "Light headed sideways to the nosy person right there doesn't.",
    "match": "nosy"
  },
  {
    "word": "armor",
    "ipa": "/ˈɑrmər/",
    "image": "assets/images/44-armor.jpg",
    "imageAlt": "armor",
    "audio": "assets/audio/44-armor.mp3",
    "definition": "protective covering for vehicles or people",
    "zh": "装甲",
    "sentenceZh": "我们每年用大量钻石来磨,钻,切飞机,坦克和装甲的部件.",
    "sentence": "We use carats of diamonds a year to grind and drill and cut parts for airplanes and tanks and armor.",
    "match": "armor"
  },
  {
    "word": "flux",
    "ipa": "/ˈflʌks/",
    "image": "assets/images/45-flux.jpg",
    "imageAlt": "flux",
    "audio": "assets/audio/45-flux.mp3",
    "definition": "a substance added to help melting",
    "zh": "助熔剂",
    "sentenceZh": "方法是用超纯碳粉,加入金属助熔剂,然后加热.",
    "sentence": "It works by taking a super pure carbon powder, adding metal flux, and then heating it up.",
    "match": "flux"
  },
  {
    "word": "molten",
    "ipa": "/ˈmoʊltən/",
    "image": "assets/images/46-molten.jpg",
    "imageAlt": "molten",
    "audio": "assets/audio/46-molten.mp3",
    "definition": "melted by great heat",
    "zh": "熔化的",
    "sentenceZh": "加热到上千摄氏度,形成像地幔里那样的熔融混合物.",
    "sentence": "It heats it up to over a thousand degrees celsius to create a molten mix like in the mantle.",
    "match": "molten"
  },
  {
    "word": "squish",
    "ipa": "/ˈskwɪʃ/",
    "image": "assets/images/47-squish.jpg",
    "imageAlt": "squish",
    "audio": "assets/audio/47-squish.mp3",
    "definition": "to squeeze or squash",
    "zh": "挤压",
    "sentenceZh": "这台机器用强力机械臂把它挤压在一起产生压力.",
    "sentence": "This machine uses powerful arms to squish it together, creating pressure.",
    "match": "squish"
  },
  {
    "word": "fingertip",
    "ipa": "/ˈfɪŋɡərˌtɪp/",
    "image": "assets/images/48-fingertip.jpg",
    "imageAlt": "fingertip",
    "audio": "assets/audio/48-fingertip.mp3",
    "definition": "the tip of a finger",
    "zh": "指尖",
    "sentenceZh": "压力相当于把一架客机放在你的指尖上.",
    "sentence": "That's pressure equivalent to placing a commercial airplane on your fingertip.",
    "match": "fingertip"
  },
  {
    "word": "puck",
    "ipa": "/ˈpʌk/",
    "image": "assets/images/49-puck.jpg",
    "imageAlt": "puck",
    "audio": "assets/audio/49-puck.mp3",
    "definition": "a small flat round object",
    "zh": "圆盘,冰球",
    "sentenceZh": "你把它放在这个耐热金属圆盘上.",
    "sentence": "You place it on this heat resistant metal puck.",
    "match": "puck"
  },
  {
    "word": "hydrogen",
    "ipa": "/ˈhaɪdrədʒən/",
    "image": "assets/images/50-hydrogen.jpg",
    "imageAlt": "hydrogen",
    "audio": "assets/audio/50-hydrogen.mp3",
    "definition": "the lightest chemical element",
    "zh": "氢",
    "sentenceZh": "然后通入氢气,帮助晶体生长.",
    "sentence": "Then they add hydrogen gas. That's what's going to help build the crystal.",
    "match": "hydrogen"
  },
  {
    "word": "plasma",
    "ipa": "/ˈplæzmə/",
    "image": "assets/images/51-plasma.jpg",
    "imageAlt": "plasma",
    "audio": "assets/audio/51-plasma.mp3",
    "definition": "a hot ionized gas",
    "zh": "等离子体",
    "sentenceZh": "微波给氢分子供能,形成等离子气体云.",
    "sentence": "These microwaves give hydrogen molecules energy, creating a cloud of plasma gas.",
    "match": "plasma"
  },
  {
    "word": "methane",
    "ipa": "/ˈmɛθeɪn/",
    "image": "assets/images/52-methane.jpg",
    "imageAlt": "methane",
    "audio": "assets/audio/52-methane.mp3",
    "definition": "a gas made of carbon and hydrogen",
    "zh": "甲烷",
    "sentenceZh": "最后的原料是碳,通过加入甲烷气体获得.",
    "sentence": "Now, final ingredient, you need carbon. And you get it by adding methane gas.",
    "match": "methane"
  },
  {
    "word": "breakthrough",
    "ipa": "/ˈbreɪkˌθru/",
    "image": "assets/images/53-breakthrough.jpg",
    "imageAlt": "breakthrough",
    "audio": "assets/audio/53-breakthrough.mp3",
    "definition": "a sudden important advance",
    "zh": "突破",
    "sentenceZh": "这是惊人的突破性消息.",
    "sentence": "This is incredible breakthrough news.",
    "match": "breakthrough"
  },
  {
    "word": "craving",
    "ipa": "/ˈkreɪvɪŋ/",
    "image": "assets/images/54-craving.jpg",
    "imageAlt": "craving",
    "audio": "assets/audio/54-craving.mp3",
    "definition": "a strong desire",
    "zh": "渴望",
    "sentenceZh": "如今的应用渴望温度再降 2°C.",
    "sentence": "Today's applications are craving for a 2°C reduction in temperature.",
    "match": "craving"
  },
  {
    "word": "scrap",
    "ipa": "/ˈskræp/",
    "image": "assets/images/55-scrap.jpg",
    "imageAlt": "scrap",
    "audio": "assets/audio/55-scrap.mp3",
    "definition": "to discard as waste",
    "zh": "报废,当废品",
    "sentenceZh": "你没法把它当废品......算了.",
    "sentence": "You can't scrap it. Never mind.",
    "match": "scrap"
  },
  {
    "word": "mimic",
    "ipa": "/ˈmɪmɪk/",
    "image": "assets/images/56-mimic.jpg",
    "imageAlt": "mimic",
    "audio": "assets/audio/56-mimic.mp3",
    "definition": "to imitate",
    "zh": "模仿",
    "sentenceZh": "我们找到了模仿地球内部的方法,去创造更大的东西.",
    "sentence": "We figured out how to mimic the inside of our planet to make something much bigger.",
    "match": "mimic"
  }
];
